//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService
{
    using System;
    using System.Collections.Generic;
    
    public partial class productinventory
    {
        public int ProductID { get; set; }
        public short LocationID { get; set; }
        public string Shelf { get; set; }
        public sbyte Bin { get; set; }
        public short Quantity { get; set; }
        public byte[] rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
